import './globals.css'

import type { Metadata } from 'next'

import { Footer } from '@/app/_components/footer'
import { fontSans } from '@/app/_lib/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type RootLayoutProps = Readonly<{ children: React.ReactNode }>

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={fontSans.variable}>
      <body className="dark">
        <div className="flex h-screen flex-col">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
