import './globals.css'

import type { Metadata } from 'next'

import { fontSans } from '@/app/_lib/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type RootLayoutProps = Readonly<{ children: React.ReactNode }>

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={fontSans.variable}>{children}</body>
    </html>
  )
}
